package io.github.psd2live.application

import io.github.psd2live.core.*
import io.github.psd2live.project.*
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.json.*
import org.junit.jupiter.api.io.TempDir
import org.umamo.format.art.*
import org.umamo.format.png.PngCodec
import org.umamo.format.raster.RasterImage
import java.nio.file.Files
import java.nio.file.Path
import kotlin.test.*

/**
 * A classification change after a split regenerates the rig: with a mesh input saved before the split (a mesh
 * rebuilt by a paint copies the generation input of its time), and with an image imported after the hair checkpoint.
 */
class ClassifyAfterSplitTest {
	@TempDir lateinit var temporary: Path
	private val builder = WorkspacePreviewBuilder()

	@AfterTest fun forget() { MaterializedRigStore.clear() }

	private fun layer(id: String, name: String, order: Int, bounds: LayerBounds) = WorkspaceSourceLayer(LayerId(id), name, "",
		SourceLayerKind.Raster, true, order, bounds, 1f, false, LayerBlend.Normal, ChannelMask.ALL,
		LayerRaster(bounds.width, bounds.height, ByteArray(bounds.width * bounds.height * 4) { if (it % 4 == 3) 255.toByte() else 120 }),
		null, null, false)

	private fun classify(runtime: WorkspaceRuntime<RigPreviewModel>, id: String, tag: String) = runBlocking {
		val capture = runtime.capture()
		WorkspaceDocumentCommands(runtime).execute(capture.projectId, capture.state, "Classify", listOf(WorkspaceDocumentOperation("layer_classify",
			buildJsonObject { put("layer_id", id); put("type", "PRESET"); put("role", tag) })), MutationAuthor.USER).capture
	}

	@Test fun aSplitDocumentReclassifiesWithAnOlderMeshInputAndANewImport() = runBlocking<Unit> {
		val source = WorkspaceSourceArt(64, 64, listOf(layer("hair", "Back hair", 0, LayerBounds(16, 8, 32, 48)),
			layer("face", "Face", 1, LayerBounds(20, 12, 24, 24))), emptyList())
		val document = WorkspaceDocument(source, emptyMap(), emptySet(), mapOf(
			"hair" to LayerClassificationOverride(type = LayerType.PRESET, tag = SemanticTag.BACK_HAIR),
			"face" to LayerClassificationOverride(type = LayerType.PRESET, tag = SemanticTag.FACE),
		), emptyMap(), RigEditOverlay.Empty, WorkspaceSettingsCodec.encode(PipelineConfig(atlasSize = 256, exportMoc3 = false)))
		val runtime = WorkspaceRuntime<RigPreviewModel>({ builder.build(it) }, rebuildFrom = { next, previous -> builder.build(next, previous) })
		runtime.install(runtime.state.value.state, "project", document, builder.build(document))
		val start = runtime.capture()
		val split = WorkspacePartitionCommands(runtime).execute(start.projectId, start.state, listOf(
			WorkspaceDocumentOperation("source_split_polygon", buildJsonObject {
				put("layer_id", "hair"); putJsonArray("names") { add("Left"); add("Right") }; putJsonArray("piece_ids") { add("left"); add("right") }
				putJsonArray("polygon") { listOf(0 to 0, 32 to 0, 32 to 64, 0 to 64).forEach { (x, y) -> add(buildJsonArray { add(x); add(y) }) } }
			})), "Split", MutationAuthor.USER).commit.capture
		val hair = WorkspaceSimulationCommands(runtime).execute(split.projectId, split.state,
			WorkspaceDocumentOperation("model_apply_preset", buildJsonObject { put("preset", "back_hair") }), "Hair simulation",
			MutationAuthor.USER, autoBake = false).commit.capture
		assertTrue(hair.document.rigEdits.authoringJournal.any(RigCheckpoint::isRecord))

		// The mesh input as a paint that rebuilt the face's mesh saved it: the pre-split layers, the split pieces absent.
		val older = hair.document.copy(meshSource = source)
		runtime.install(runtime.state.value.state, "project", older, builder.build(older), discardUnsaved = true)
		val reclassified = classify(runtime, "face", "TOPWEAR")
		assertEquals(SemanticTag.TOPWEAR, reclassified.model.analysis.layers.single { it.source.id.raw == "face" }.semantic.tag)

		// An image imported now is generated by the base: the regeneration merge gives it its mesh after the checkpoint.
		val file = temporary.resolve("patch.png").also { Files.write(it, PngCodec.write(RasterImage(8, 8, ByteArray(8 * 8 * 4) { -1 }))) }
		val capture = runtime.capture()
		val id = WorkspaceImageLayerCommands(runtime).importImages(capture.projectId, capture.state, listOf(file), null, "Import", MutationAuthor.USER)
			.mutation.affectedLayerIds.single()
		val imported = classify(runtime, id, "OBJECTS")
		assertTrue(imported.model.rig.layerIdByDrawableId.values.contains(id))
	}
}
